# Generated by Django 4.1.13 on 2024-01-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API1App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('year_founded', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Drink',
        ),
    ]
